// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/common/underLineToCamelCase":{"path":"common/under-line-to-camel-case","id":"docs/common/underLineToCamelCase","parentId":"DocLayout"},"docs/common/getGenderByIdNumber":{"path":"common/get-gender-by-id-number","id":"docs/common/getGenderByIdNumber","parentId":"DocLayout"},"docs/common/voiceAnnouncements":{"path":"common/voice-announcements","id":"docs/common/voiceAnnouncements","parentId":"DocLayout"},"docs/common/getSecretIdNumber":{"path":"common/get-secret-id-number","id":"docs/common/getSecretIdNumber","parentId":"DocLayout"},"docs/common/formatWithCommas":{"path":"common/format-with-commas","id":"docs/common/formatWithCommas","parentId":"DocLayout"},"docs/common/getAgeByIdNumber":{"path":"common/get-age-by-id-number","id":"docs/common/getAgeByIdNumber","parentId":"DocLayout"},"docs/common/getSecretPhone":{"path":"common/get-secret-phone","id":"docs/common/getSecretPhone","parentId":"DocLayout"},"docs/common/simpleDebounce":{"path":"common/simple-debounce","id":"docs/common/simpleDebounce","parentId":"DocLayout"},"docs/common/getSecretName":{"path":"common/get-secret-name","id":"docs/common/getSecretName","parentId":"DocLayout"},"docs/common/isEmptyValue":{"path":"common/is-empty-value","id":"docs/common/isEmptyValue","parentId":"DocLayout"},"docs/common/percentCut":{"path":"common/percent-cut","id":"docs/common/percentCut","parentId":"DocLayout"},"docs/common/getRandom":{"path":"common/get-random","id":"docs/common/getRandom","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/chenshuhang/Documents/alito/uitls/node_modules/.pnpm/dumi@2.4.12_prettier@2.8.8/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/chenshuhang/Documents/alito/uitls/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/chenshuhang/Documents/alito/uitls/node_modules/.pnpm/dumi@2.4.12_prettier@2.8.8/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/common/underLineToCamelCase': React.lazy(() => import(/* webpackChunkName: "docs__common__underLineToCamelCase.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/underLineToCamelCase.md')),
'docs/common/getGenderByIdNumber': React.lazy(() => import(/* webpackChunkName: "docs__common__getGenderByIdNumber.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/getGenderByIdNumber.md')),
'docs/common/voiceAnnouncements': React.lazy(() => import(/* webpackChunkName: "docs__common__voiceAnnouncements.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/voiceAnnouncements.md')),
'docs/common/getSecretIdNumber': React.lazy(() => import(/* webpackChunkName: "docs__common__getSecretIdNumber.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/getSecretIdNumber.md')),
'docs/common/formatWithCommas': React.lazy(() => import(/* webpackChunkName: "docs__common__formatWithCommas.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/formatWithCommas.md')),
'docs/common/getAgeByIdNumber': React.lazy(() => import(/* webpackChunkName: "docs__common__getAgeByIdNumber.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/getAgeByIdNumber.md')),
'docs/common/getSecretPhone': React.lazy(() => import(/* webpackChunkName: "docs__common__getSecretPhone.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/getSecretPhone.md')),
'docs/common/simpleDebounce': React.lazy(() => import(/* webpackChunkName: "docs__common__simpleDebounce.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/simpleDebounce.md')),
'docs/common/getSecretName': React.lazy(() => import(/* webpackChunkName: "docs__common__getSecretName.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/getSecretName.md')),
'docs/common/isEmptyValue': React.lazy(() => import(/* webpackChunkName: "docs__common__isEmptyValue.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/isEmptyValue.md')),
'docs/common/percentCut': React.lazy(() => import(/* webpackChunkName: "docs__common__percentCut.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/percentCut.md')),
'docs/common/getRandom': React.lazy(() => import(/* webpackChunkName: "docs__common__getRandom.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/common/getRandom.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/chenshuhang/Documents/alito/uitls/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/chenshuhang/Documents/alito/uitls/node_modules/.pnpm/dumi@2.4.12_prettier@2.8.8/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
