// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/chenshuhang/Documents/alito/uitls/node_modules/.pnpm/dumi@2.4.12_prettier@2.8.8/node_modules/dumi/theme-default/slots/Hero/index.js';
